# Generated by Django 3.2.25 on 2025-05-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250504_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
